# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(db_index=True, default=0)),
                ('task_server', models.IntegerField(db_index=True, default=0)),
                ('task_start_date', models.DateTimeField()),
                ('task_update_date', models.DateTimeField()),
                ('task_wait_confirm', models.BooleanField()),
                ('task_url', models.CharField(max_length=2048)),
                ('task_addon_type', models.IntegerField(default=0)),
                ('task_addon_bucket', models.CharField(max_length=255)),
                ('task_addon_key', models.CharField(max_length=1024)),
                ('task_addon_cookie', models.CharField(max_length=2048)),
            ],
        ),
    ]
