# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_server', models.CharField(db_index=True, max_length=80)),
                ('task_start_date', models.DateTimeField()),
                ('task_update_date', models.DateTimeField()),
                ('task_progress', models.IntegerField(default=0)),
                ('task_status', models.IntegerField(db_index=True, default=0)),
                ('task_type', models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
