# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtask',
            name='task_server_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
