# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.IntegerField(db_index=True, default=0)),
                ('server_uid', models.CharField(db_index=True, max_length=80)),
                ('server_name', models.CharField(default='', max_length=255)),
                ('start_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('current_download', models.IntegerField(default=0)),
                ('finish_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
            ],
        ),
    ]
